# Generated by Django 2.2.7 on 2019-11-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='profile_picture/')),
                ('fk_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbapp.Login')),
            ],
        ),
    ]
